[package]
name = "amodinfo"
version = "0.1.0"
authors = [
    "Mårten Kongstad <marten.kongstad@gmail.com>",
]
edition = "2021"

[dependencies]
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]
